# Site settings
title: Moody Salem's Blog
motto: Write Less Code
email: moody.salem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My placeholder blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moodysalem.com" # the base hostname & protocol for your site
github_username:  moodysalem

# Build settings
markdown: kramdown
