# Site settings
title: Code Less
email: moody.salem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Working as a Software Engineer mainly with Java technologies, experimenting with AWS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moodysalem.com" # the base hostname & protocol for your site
github_username:  moodysalem

# Build settings
markdown: kramdown
