# Site settings
title: Moody Salem's Blog
motto: Write Less Code
email: moody.salem@gmail.com
description: A blog about getting things done as a lazy developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moodysalem.com" # the base hostname & protocol for your site
github_username:  moodysalem

# Build settings
markdown: kramdown
