# Site settings
title: Moody Salem's Blog
motto: less code
email: moody.salem@gmail.com
description: Chicago based Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moodysalem.com" # the base hostname & protocol for your site
github_username:  moodysalem

# Build settings
markdown: kramdown
